id: P67726B61
initial_creation_type: input
source_metadata:
  title: Jamyang Khyentse Wangpo Series
  language: en
  description: 'Texts by and about the great Rimé (“nonsectarian”) master Jamyang
    Khyentse Wangpo (''jam dbyangs mkhyen brtse''i dbang po, 1820–1892), one of the
    most influential figures of recent times:'
  volume:
    52832ab3188c490ba5e1293b97f3c935:
      title: 'A Few Words of Commentary to Clarify The Essence of Nectar: Graduated
        Stages of the Path—Advice for Renunciant Meditators'
      parent: Advice
    342b067899104ccda5462e9b51f748ff:
      title: 'The Essence of Nectar: Graduated Stages of the Path — Advice for Renunciant
        Meditators'
      parent: Advice
    079cc983401c4afdbcf56b1bbbc660e9:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    697fc1aa49fd4d8e8564ce38abdcf361:
      title: The Life of Jamyang Khyentse Wangpo
      parent: Biography
    b21a0edcc8744b9aa0478a50584d47d1:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: Buddhist Philosophy
    ba2c1445f3724d5a8223437015cfba5c:
      title: 'A Few Remarks: An Explanation of the Praise to Noble Mañjuśrī known
        as Glorious Wisdom’s Excellent Qualities'
      parent: Commentaries
    1e314aa8e05e465a8ace402278c16175:
      title: Guide to the Practice of Narak Kong Shak
      parent: Confession
    17ce76498a2a444f9107fa8e32d54b19:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      parent: Consecration
    2518a774fccb4743b9ef529131574f3c:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Fulfilment
    ad5693b9c3284cff921bd3cf07075d00:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
    8aab0b4bf6ff400c85023da805d04656:
      title: A Brief History of the Sacred Image of White Tārā
      parent: History
    b7baf11596be47a2a0b640be4a325c6a:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: History
    bee0ad53c912436ea0dfe63051e1dde0:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    52a82372f0d4403a8d9939555c5eaf3d:
      title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the
        Profound Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
      parent: Lineage Prayers
    9a2c706ed83147b384419a729dab5764:
      title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret
        Practice of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Lineage Prayers
    4bcf01df20be40128276bf65b84e43fe:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    1db0fa8f616145c69b4484218ea893d8:
      title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s
        Teachings in Tibet'
      parent: Lineage Prayers
    cef7a1be825b4458a35a5bb68ba7731e:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    4f7b7544ff3c4df49fa03501b21bae8c:
      title: 'The Seed of Faith: A Prayer to the Sublime Ones'
      parent: Lineage Prayers
    6ba2b68748634d848ccf06e1e1b6ded7:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Lineage Prayers
    e158ed89790049479141778125eb34b8:
      title: Ambrosia for the Mind
      parent: Lojong
    c81d6b13f6a14da88493f85021cb37b1:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Lojong
    2634c5ef34904e8090de1a5867e58b31:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Longevity
    150efe60393043aca7864a078f86f373:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Mañjuśrī
    437fc248762b4ebd857d2c5a5c14e4aa:
      title: 'A Profound Concentration of Nectar: Essentialized Stages of Visualization
        for the Preliminary Practices of the Heart Essence of the Vast Expanse (Longchen
        Nyingtik)'
      parent: Ngöndro
    08114a50d7a4478d8c957c8c43d8a7ad:
      title: 'Illuminating the Excellent Path to Omniscience: Notes on the Longchen
        Nyingtik Ngöndro'
      parent: Ngöndro
    fb25ec450ccb4b4983092452e56dc703:
      title: 'The Excellent Path to Enlightenment: A Brief Practice of the Preliminaries'
      parent: Ngöndro
    2d8ffd6b9249482da0007d92674cf04a:
      title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
      parent: Offering
    b6f7d0762a6c4f6693f846ec309c0aba:
      title: Concise Seven-Heap Maṇḍala Offering
      parent: Offering
    086d05de320a4b679b0510f9f517a82f:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Offering
    72fd9ba955d849ceba4c07e5682be3e0:
      title: Short Maṇḍala Offering
      parent: Offering
    3c151e63d57c43489b43dde459d71064:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Offering
    1dae99cec57e4062bf6b66fcc6b33135:
      title: In Praise of Jamyang Khyentse Wangpo
      parent: Praise
    02089415d1cc4226ade28a56a65efdce:
      title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
      parent: Praise
    4fabc02f2fce4a5fa87610f7b7ab90ec:
      title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
        Jamyang Khyentse Wangpo
      parent: Prayers
    8b5880f7cb634ac5b5bd4ffbb9e3e13d:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    dce1ff4fecfa45d69759502aa9424bd9:
      title: Prayer to Jamyang Khyentse Wangpo
      parent: Prayers
    90f4e02415004cd2914d5d94c411d8cf:
      title: Prayer to Jamyang Khyentse Wangpo and Jamyang Khyentse Chökyi Lodrö
      parent: Prayers
    f5efaf98ffff448ab36092821fdff7ce:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    7879e1fd8a7f47068f3004f6f0409180:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    4b7ecf2ac9ef41ee8c1669e983a4e63d:
      title: Prayer to Root and Lineage Masters, and the Assembly of Deity, Ḍākinīs
        and Dharma Protectors of the Sakya Lineage
      parent: Prayers
    b6b454f6ec304d04b7281b40d66bb909:
      title: Prayer to Thangtong Gyalpo
      parent: Prayers
    3d1b5261560546249ab21f2042062767:
      title: Prayer to the Siddha Virūpa
      parent: Prayers
    838efb161e3749c59f1d995f96fb7ca7:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    96296928327645a7b613a3df26748cc8:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    f00c73d45b844270991f84c9cb33b229:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
    746c72f8f629467a91bc20817001033d:
      title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā
        Combined with Her Root Mantra'
      parent: Prayers
    3289fd188e4e476baaa0b3431666df21:
      title: Words of Jamyang Khyentse
      parent: Prayers
    d7e48394ac67481c8d8d9db0f51a88cc:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Prayers to Guru Rinpoche
    6f2585f67c454f068a70d0f82dc85a6b:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Prayers to Guru Rinpoche
    f4fcd137053a4dc08d09ac90de2c1aa7:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Prayers to Guru Rinpoche
    26dcc057f9dd4155b6d02a8ceecf737f:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Prayers to Guru Rinpoche
    95c657427dda4369a5531e3874357487:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Prayers to Guru Rinpoche
    a060c7d468394370ae2dd327ca7e274e:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Prayers to Guru Rinpoche
    33f0ba32a374482aafd0b81c7f6b84ce:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Prayers to Guru Rinpoche
    ccf7839e27314ecca35a99739942221a:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    16d5b8d0bb4548f6a18104620bd48c0b:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Sādhanas
    f3d0ae848cc946fd91f39539b43e377b:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Sādhanas
    d32fa52ffe314e028f6757dcc6a0b6c0:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
    74ec604ae3234e518a753e90ca6157a6:
      title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart
        Practice of Vidyādharas, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    b5741c2d1c264faa93c3b0825f2c1574:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    d45aaad6d3dc4d9190d8db6d3c8e45e1:
      title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
        Düpa), the Heart Practice of the Awareness-Holders'
      parent: Sādhanas
    e86782ef6c964499bd8128b92cf85e8f:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Sādhanas
    24a6438bce36469785e32d7d6dec3f2e:
      title: The Visualization of the Four Goddesses of the Great Compassionate One,
        Natural Liberation of Suffering
      parent: Sādhanas
    798492ec0d18496e99815077b9154a5f:
      title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
      parent: Saving Lives
    10b9e186a1da4a44a6bfffc47bd2b9f6:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    9475b1297a0449fe843cebdae56e59e2:
      title: The Twenty-Eight Commitments
      parent: Tantra
    6ae4b9393cea42ff8112c29b5b8c5e00:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Tsok
    474fb91e1f7b4d0c814b57da5226f8bb:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Tsok
    49f2a2ca6c6e442c972677d0b7be2d92:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Tsok
    dee88a4054714db1a6f0c9f6c4fdb4c6:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Tsok
    be9732857cd74fa3a4b40f279b8fa35e:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Tsok
created_at: '2022-02-28T23:57:51.890918'
last_modified_at: '2022-02-28T23:57:51.890924'
